name: crypto_news_sinhala
description: "A Flutter project for crypto news in Sinhala."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS styling
  cupertino_icons: ^1.0.8

  # Firebase core for initializing Firebase
  firebase_core: ^3.10.1

  # Firebase Authentication for user login/signup
  firebase_auth: ^5.4.1

  # Cloud Firestore for database
  cloud_firestore: ^5.6.2

  # Firebase Storage for storing images/files
  firebase_storage: ^12.4.1

  # Firebase Messaging for push notifications
  firebase_messaging: ^15.2.1

  # HTTP package for API requests
  http: ^1.0.0

  # State management (using Provider)
  provider: ^6.0.0

  # URL launcher for opening affiliate links
  url_launcher: ^6.1.10

  # Cached network image for efficient image loading
  cached_network_image: ^3.2.3

  # For responsive UI
  flutter_screenutil: ^5.0.0

  # For navigation
  go_router: ^14.7.1

  # Vector Icons
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets for images or other static files
  assets:
    - assets/images/ # Add your images here
